trigger: none

pool:
  name: Default

variables:
  AWS_REGION: "ap-south-1"
  EKS_CLUSTER_NAME: "devops-platform"

steps:
  - script: |
      set -x
      aws eks update-kubeconfig --region $(AWS_REGION) --name $(EKS_CLUSTER_NAME)
    displayName: "Configure kubeconfig For EKS"
  
  - script: |
      set -x

      kubectl get nodes

    displayName: "Validate EKS Connectivity"

  - script: |
      set -x

      cd helm/sample-node-app

      helm upgrade --install sample-node-app .

    displayName: "Deploy Application Using Helm"

  - script: |
      set -x

      kubectl get pods
      kubectl get svc
      kubectl get ingress

    displayName: "Validate Kubernetes Deployment"