trigger:
  - main

pool:
  name: Default

steps:
  - script: |
      echo "Pipeline Started"

      echo "Checking Node.js Version"
      node -v

      echo "Checking npm Version"
      npm -v
    displayName: "Validate Node.js Environment"

  - script: |
      cd app

      echo "Current Directory:"
      pwd

      echo "Listing Application Files"
      ls -l

      echo "Installing Dependencies"
      npm install
    displayName: "Install Node.js Dependencies"