trigger:
  - main

pool:
  name: Default

steps:
  - script: |
      set -x
      echo "Checking Node.js"
      node -v

      echo "Checking npm"
      npm -v
    displayName: "Validate Node.js Environment"

  - script: |
      set -x
      cd app

      echo "Installing Dependencies"
      npm install
    displayName: "Install Node.js Dependencies"

  - script: |
      set -x
      echo "Checking Docker"
      docker --version
    displayName: "Validate Docker Environment"

  - script: |
      set -x   
      echo "Building Docker Image"

      docker build \
        -t sample-node-app:v1 \
        -f Dockerfile .
    displayName: "Build Docker Image"

  - script: |
      set -x
      docker images
    displayName: "Verify Docker Image"