apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-node-app
  name: sample-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
      - image: sample-node-app:v3
        imagePullPolicy: Never
        name: sample-node-app
        resources: {}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: sample-node-config
        - secretRef:
            name: sample-node-secret
status: {}
