apiVersion: v1
kind: ConfigMap

metadata:
  name: sample-node-config

data:
  APP_ENV: "{{ .Values.config.appEnv }}"
  APP_VERSION: "{{ .Values.config.appVersion }}"
  APP_MESSAGE: "Running from ConfigMap"