apiVersion: v1
kind: Service

metadata:
  name: sample-node-service

spec:
  selector:
    app: sample-node-app

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}

  type: {{ .Values.service.type }}